version: "3"
name: "minecraft-server"
services:
  minecraft:
    image: "itzg/minecraft-server:latest"
    network_mode: "bridge"
    environment:
      - EULA=TRUE
      - WHITELIST=zacari23 # comma separated list
      - TZ=America/Los_Angeles
      - MODE=survival
      - VIEW_DISTANCE=16
      - DIFFICULTY=normal
      - LEVEL_TYPE=default
      - MODRINTH_PROJECTS=lithium,simple-voice-chat
      - MAX_PLAYERS=10
      - OPS=zacari23 # comma separated list
      - MEMORY=7G
      - SEED=-390989114756324017
      - VERSION=1.21
      - TYPE=FABRIC
    volumes: # Make sure this matches the mounts in docker desktop (or similar product you're using to run)
      - "~/Documents/Minecraft/server:/data"
    ports:
     - "25565:25565" # Minecraft main port - TCP
     - "24454:24454" # Simple Voice Chat -- UDP

